/*
Copyright Tapajit Chandra Paul.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	fullmetalcomv1 "github.com/tapojit047/CRD-Controller/pkg/apis/fullmetal.com/v1"
	versioned "github.com/tapojit047/CRD-Controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/tapojit047/CRD-Controller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/tapojit047/CRD-Controller/pkg/client/listers/fullmetal.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AlchemistInformer provides access to a shared informer and lister for
// Alchemists.
type AlchemistInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.AlchemistLister
}

type alchemistInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAlchemistInformer constructs a new informer for Alchemist type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAlchemistInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAlchemistInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAlchemistInformer constructs a new informer for Alchemist type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAlchemistInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FullmetalV1().Alchemists(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FullmetalV1().Alchemists(namespace).Watch(context.TODO(), options)
			},
		},
		&fullmetalcomv1.Alchemist{},
		resyncPeriod,
		indexers,
	)
}

func (f *alchemistInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAlchemistInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *alchemistInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&fullmetalcomv1.Alchemist{}, f.defaultInformer)
}

func (f *alchemistInformer) Lister() v1.AlchemistLister {
	return v1.NewAlchemistLister(f.Informer().GetIndexer())
}
